// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvnOU8M5Iig-Mfe61lNFDI6c7bEZNSBk',
    appId: '1:575253291767:web:99d089008fa2e31ef3a9f2',
    messagingSenderId: '575253291767',
    projectId: 'storanova-1199c',
    authDomain: 'storanova-1199c.firebaseapp.com',
    storageBucket: 'storanova-1199c.firebasestorage.app',
    measurementId: 'G-BSG2LDJELB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN0p0H7kWAdrw86diR4bWdRL2FA1FRNvM',
    appId: '1:575253291767:android:9fb396d5e6a4c944f3a9f2',
    messagingSenderId: '575253291767',
    projectId: 'storanova-1199c',
    storageBucket: 'storanova-1199c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJn4bRvaghuOEgYABpnmszV3J45PJRrn8',
    appId: '1:575253291767:ios:d16877f4472623f9f3a9f2',
    messagingSenderId: '575253291767',
    projectId: 'storanova-1199c',
    storageBucket: 'storanova-1199c.firebasestorage.app',
    iosBundleId: 'com.example.projectStoranova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJn4bRvaghuOEgYABpnmszV3J45PJRrn8',
    appId: '1:575253291767:ios:d16877f4472623f9f3a9f2',
    messagingSenderId: '575253291767',
    projectId: 'storanova-1199c',
    storageBucket: 'storanova-1199c.firebasestorage.app',
    iosBundleId: 'com.example.projectStoranova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBvnOU8M5Iig-Mfe61lNFDI6c7bEZNSBk',
    appId: '1:575253291767:web:1a484340d6a5d654f3a9f2',
    messagingSenderId: '575253291767',
    projectId: 'storanova-1199c',
    authDomain: 'storanova-1199c.firebaseapp.com',
    storageBucket: 'storanova-1199c.firebasestorage.app',
    measurementId: 'G-0790BDWE6B',
  );
}
